# Generated by Django 6.0.6 on 2026-07-08 09:00

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField(default=datetime.date(1900, 1, 1))),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Activo_en_portafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(blank=True, editable=False, null=True)),
                ('peso', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portafolios', to='portafolio.activos')),
            ],
        ),
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('activos', models.ManyToManyField(related_name='portafolios_relacionados', through='portafolio.Activo_en_portafolio', to='portafolio.activos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='activo_en_portafolio',
            name='portafolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activos_en_portafolio', to='portafolio.portafolio'),
        ),
        migrations.AlterUniqueTogether(
            name='activo_en_portafolio',
            unique_together={('portafolio', 'activo')},
        ),
        migrations.CreateModel(
            name='ValorHistoricoPortafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=100, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('portafolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_historicos', to='portafolio.portafolio')),
            ],
            options={
                'ordering': ['fecha'],
                'unique_together': {('portafolio', 'fecha')},
            },
        ),
    ]
